name: march_tales_app
description: March Tales mobile application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.11

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  # english_words: ^4.0.0  # TODO: To remove (debug only)
  provider: ^6.0.0
  http: ^1.2.2
  flutter_launcher_icons: ^0.14.2
  logger: ^2.5.0
  fluttertoast: ^8.2.10
  flutter_localizations:
    sdk: flutter
  intl: any
  i18n_extension: ^15.0.3
  cached_network_image: ^3.4.1
  shared_preferences: ^2.4.0
  url_launcher: ^6.3.1
  audio_service: ^0.18.17
  just_audio: ^0.9.44
  just_audio_background: ^0.0.1-beta.15
  sqflite: ^2.4.1
  path: ^1.9.0
  event: ^3.1.0
  flutter_inappwebview: ^6.1.5
  flutter_svg: ^2.0.17
  android_notification_icons: ^0.0.1
  # flutter_local_notifications: ^18.0.1
  # firebase_core: ^3.12.1
  # firebase_auth: ^5.5.1
  # google_sign_in: ^6.2.2

dev_dependencies:
  test: ^1.25.8
  flutter_test:
    sdk: flutter

  # @see https://docs.flutter.dev/release/breaking-changes/flutter-lints-package
  # Use shell command: `dart format . && dart analyze .`
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0

# @see https://pub.dev/documentation/import_sorter/latest/
import_sorter:
  emojis: true # Optional, defaults to false
  comments: false # Optional, defaults to true
  # ignored_files: # Optional, defaults to []
  #   - \/lib\/*

android_notification_icons:
  image_path: "assets/launcher/cat-icon-white-transp-1024.png"
  icon_name: 'ic_notification' # optional

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/lobster/lobster.ttf

  assets:
    - assets/
    - assets/images/march-cat/march-cat-sq-48.jpg
    - assets/images/march-cat/cat-icon.svg
    - assets/images/march-cat/cat-icon-48.png
    - assets/project-info.json
    # - assets/fonts/ # TODO: Use lobser font for titles

