// Automatic translation keys for the i18n_extension package.
// Generated by the i18n_extension package.
// Do not edit this file manually, instead edit the translation files (.arb) in the l10n folder.

import 'package:i18n_extension/i18n_extension.dart';

extension Localization on String {
  static var _t = Translations.byLocale('en') +
      {
        'ru': {
          'Series: {series_name}': 'Серия: {series_name}',
          'Loading series...': 'Загрузка серии...',
          'Error loading series data': 'Ошибка загрузки данных о серии',
          'No series data found': 'Данные о серии не найдены',
        },
      };
  String get i18n => localize(this, _t);
}
